version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: htmx-gotempl-app
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge